config/routes.rb
Rails.application.routes.draw do

  resources :tags

  root 'creatures#index'

  resources :creatures

  get 'creatures/tag/:tag' => 'creatures#tag', as: :creature_tag

end

app/models/bog.rb
class Bog < ActiveRecord::Base
end

app/models/creature.rb
class Creature < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :creatures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController


  def index
    @creatures = Creature.all
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def show
    @creature = Creature.find(params[:id])
    @tags = @creature.tags
    list = flickr.photos.search :text => @creature.name, :sort => "relevance"
    results = list.map do |photo|
      "https:/farm3.static.flickr.com/#{photo["server"]}/""#{photo["id"]}_""#{photo["secret"]}_n.jpg"
    end
    @result = results
  end


  def create
    @creature = Creature.create(creature_params)
    tags = params[:creature][:tag_ids]
    tags.each do |tag_id|
      @creature.tags << Tag.find(tag_id) unless tag_id.blank?
    end
    redirect_to @creature
  end

  def creature_params
  params.require(:creature).permit(:name,:description)
  end

  def edit
    @creature = Creature.find(params[:id])
    @tags = Tag.all
  end

  def update
    @creature = Creature.find(params[:id])
    @creature.update(creature_params)
    @tags = Tag.all
    @creature.tags.clear
    tags = params[:creature][:tag_ids]
    tags.each do |tag_id|
      @creature.tags << Tag.find(tag_id) unless tag_id.blank?
    end
    redirect_to @creature
  end

  def tag
    tag = Tag.find_by_name(params[:tag])
    @creatures = tag.creatures
  end

  def destroy
    @creature = Creature.find(params[:id])
    @creature.destroy
    redirect_to creatures_path
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tags = Tag.all
    @tag = Tag.new()
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

  def create
    @tag = Tag.create(tag_params)
    redirect_to :tags
  end

  def update
  end

  def edit
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

  def index
    @tags = Tag.all
  end

  def show
    @creature = Creature.find(params[:id])
    @tags = @creature.tags
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_controller_helper.rb
module TagsControllerHelper
end

app/views/creatures/edit.html.erb
<div class="container">
  <h1>Edit the info here:</h1>
  <div class="row">
      <%= bootstrap_form_for @creature do |f| %>
      <%= f.text_field :name, :placeholder => "Enter a name"%>
      <%= f.text_field :description, :placeholder => "Enter a description" %>
      <%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
      <%= f.submit "Update", class: "btn" %>
      <% end %>
  </div>
</div>

app/views/creatures/index.html.erb
<div class="container">

<h1>Creatures of the Bog</h1>

  <table class="AllCreaturesTable">
  <tr>
    <th>Creature</th>
    <th>Description</th>
  </tr>
<% @creatures.each do |c| %>
  <tr>
    <td><%= link_to c.name, c %></td>
    <td><%= c.description %></td>
    <td><%= link_to "Update", edit_creature_path(c), class: "btn" %></td>
    <td><%= link_to "Delete", creature_path(c), class: "btn", method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
<% end %>
</table>
</div>

app/views/creatures/new.html.erb
<div class="container">
  <h1>Enter a new creature:</h1>
  <div class="row">
      <%= bootstrap_form_for @creature do |f| %>
      <%= f.text_field :name, :placeholder => "Enter a name"%>
      <%= f.text_field :description, :placeholder => "Enter a description" %>
      <%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
      <%= f.submit "Submit", class: "btn" %>
      <% end %>

  </div>
</div>

app/views/creatures/show.html.erb
<div class="container">

  <h1><%= @creature.name %> details:</h1>
  <br><br>

  <table class="oneCreatureTable">
  <tr>
    <th>Creature</th>
    <th>Description</th>
    <br>
  </tr>
  <tr>
    <td><%= @creature.name %></td>
    <td><%= @creature.description %></td>
    <% @creature.tags.each do |t| %>
    <td><%= link_to t.name, creature_tag_path(t.name) %></td>
    <% end %>
    <td><%= link_to "Update", edit_creature_path, class: "btn" %></td>
    <td><%= link_to "Delete", creature_path, class: "btn", method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
</table>
    <td><img src="<%= @result.sample %>"></td>

</div>

app/views/creatures/tag.html.erb
<div class="container">
<h2>List of all creatures that have the tag "<%= params[:tag] %>":</h2>
<% @creatures.each do |c| %>
<li><%= c.name %></li>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="body">
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/">The Bog Files</a></li>
  <li role="presentation"><a href="/creatures/new">Add a creature</a></li>
  <li role="presentation"><a href="/tags/new">Add a tag</a></li>
</ul>

<%= yield %>

</body>
</html>

app/views/tags/create.html.erb
<h1>TagsController#create</h1>
<p>Find me in app/views/tags_controller/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>TagsController#destroy</h1>
<p>Find me in app/views/tags_controller/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h1>TagsController#edit</h1>
<p>Find me in app/views/tags_controller/edit.html.erb</p>

app/views/tags/index.html.erb
<div class="container">


  <table class="AllCreaturesTable">
  <tr>
    <th>Tag</th>
  </tr>
<% @tags.each do |t| %>
  <tr>
    <td><%= link_to t.name, t %></td>
    <td><%= link_to "Delete", tag_path(t), class: "btn", method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
<% end %>
</table>
</div>

app/views/tags/new.html.erb
<div class="container">
  <h1>Add a new tag:</h1>
  <div class="row">
      <%= bootstrap_form_for @tag do |f| %>
      <%= f.text_field :name, :placeholder => "Enter a tag"%>
      <%= f.submit "Submit", class: "btn" %>
      <% end %>
      <br>
      <h3>Existing tags:</h3>
      <% @tags.each do |t| %>
      <li><%= t.name %></li>
      <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container">
<h2>List of all creatures that have the tag "<%= params[:tag] %>":</h2>
<% @creatures.each do |c| %>
<li><%= c.name %></li>
<% end %>
</div>

app/views/tags/update.html.erb
<h1>TagsController#update</h1>
<p>Find me in app/views/tags_controller/update.html.erb</p>